"""add added_by and named unique constraint

Revision ID: 8edfb75989a9
Revises: fa12f56ce842
Create Date: 2026-10-01 14:40:05.686680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edfb75989a9'
down_revision = 'fa12f56ce842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_opinion_timestamp'), ['timestamp'], unique=False)
        batch_op.create_unique_constraint('uq_opinion_text', ['text'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_constraint('uq_opinion_text', type_='unique')
        batch_op.drop_index(batch_op.f('ix_opinion_timestamp'))
        batch_op.drop_column('added_by')

    # ### end Alembic commands ###
