"""added added_by field

Revision ID: fa12f56ce842
Revises: 
Create Date: 2026-10-01 14:22:04.033834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa12f56ce842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_opinion_timestamp'), ['timestamp'], unique=False)
        batch_op.create_unique_constraint(None, ['text'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_opinion_timestamp'))
        batch_op.drop_column('added_by')

    # ### end Alembic commands ###
